
// Objective-C API for talking to the following Go packages
//
//	appbricks.io/gomobiletest/greeter
//	appbricks.io/gomobiletest/person
//
// File is generated by gomobile bind. Do not edit.
#ifndef __User_FRAMEWORK_H__
#define __User_FRAMEWORK_H__

#include "Greeter.objc.h"
#include "Person.objc.h"
#include "Universe.objc.h"

#endif
