// Objective-C API for talking to appbricks.io/gomobiletest/greeter Go package.
//   gobind -lang=objc appbricks.io/gomobiletest/greeter
//
// File is generated by gobind. Do not edit.

#ifndef __Greeter_H__
#define __Greeter_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Person.objc.h"

@class GreeterGreeter;
@protocol GreeterPrinter;
@class GreeterPrinter;

@protocol GreeterPrinter <NSObject>
- (void)printSomething:(NSString* _Nullable)s;
@end

/**
 * Greeter greets people.
 */
@interface GreeterGreeter : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
/**
 * NewGreeter makes a new Greeter.
 */
- (nullable instancetype)init:(id<GreeterPrinter> _Nullable)printer;
/**
 * Greet greets someone.
 */
- (void)greet:(PersonPerson* _Nullable)p0;
@end

/**
 * NewGreeter makes a new Greeter.
 */
FOUNDATION_EXPORT GreeterGreeter* _Nullable GreeterNewGreeter(id<GreeterPrinter> _Nullable printer);

@class GreeterPrinter;

/**
 * Printer types can print things.
 */
@interface GreeterPrinter : NSObject <goSeqRefInterface, GreeterPrinter> {
}
@property(strong, readonly) _Nonnull id _ref;

- (nonnull instancetype)initWithRef:(_Nonnull id)ref;
- (void)printSomething:(NSString* _Nullable)s;
@end

#endif
